version: '3.4'

services:  
  demo:
    image: dianarodrix/demo
    build:
      context: demo
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    links: 
      - redis
    depends_on:
      - redis
    networks: 
      backend:
        ipv4_address: 172.20.0.2
  redis:
    image: redis:latest
    container_name: "redis"
    command: redis-server
    ports:
      - "6379:6379"
    networks: 
      backend:
        ipv4_address: 172.20.0.4
networks: 
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
   